name: Run Eventuals Example

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  run-eventuals:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. 安装 Bazelisk
    - name: Setup Bazelisk
      uses: bazelbuild/setup-bazelisk@v2
      with:
        bazelisk-version: 1.x

    # 3. 可选缓存 Bazel 构建（key 简单，避免 400）
    - name: Cache Bazel
      uses: actions/cache@v3
      with:
        path: ~/.cache/bazel
        key: bazel-${{ runner.os }}-cache

    # 4. 安装依赖（例如 git submodules 或 extern 库）
    - name: Update submodules
      run: git submodule update --init --recursive

    # 5. 构建 eventuals 程序
    - name: Build pipelines-8
      run: bazel build //:pipelines-8

    # 6. 运行 eventuals 程序并打印输出
    - name: Run pipelines-8
      run: bazel run //:pipelines-8
