name: Run Eventuals Tutorial

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  run-eventuals:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bazelbuild/setup-bazelisk@v2
    - name: Cache Bazel
      uses: actions/cache@v3
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-bazel-${{ hashFiles('**/*.bazel', '**/*.bzl') }}
    - name: Run pipelines-8
      run: bazel run :pipelines-8